name: release

on:
  push: 
    branches: [ release ]

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pdoc3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: | 
        python setup.py install
        pip install .
    - name: Test with pytest
      run: |
        pytest tests/
    - name: generate docs
      run: |
        pwd
        pdoc --html --output-dir docs PCalculator/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/PCalculator # The folder the action should deploy.
        CLEAN: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated release: {{ github.GITHUB_RUN_NUMBER }}
        draft: false
        prerelease: false